### ISSUE TITLE
Question: could not ping other site

### ISSUE THREAD

**Issue by Mannshoch** [Vilbrekin/tinc_gui#22]
I was testing around over 3G. (My data quota is not fully used so I tried to stream some Music over DLNA)
 I detected that even Tinc was able to connect i'm not able to pin an IP
Android: 10.168.10.11
Desktop: 10.168.10.12

Ping on the device itself 10.168.10.11 works but ping on 10.168.10.12 get 100% package loss

I only have Problems with my Android. Other PC can connect to Desktop.

If someone has an Idea how to repair, thanks

tinc.conf

``` ini
AddressFamily=ipv4
Name=Android
ConnectTo=Desktop
Device=/dev/tun
Interface=tun0
Mode=switch
ScriptsInterpreter = /system/bin/sh
KeyExpire = 3600
```

tinc-up

``` bash
#!/bin/sh
ifconfig $INTERFACE 10.168.10.11 netmask 255.255.255.0
echo 1 > /proc/sys/net/ipv4/conf/$INTERFACE/rp_filter
```

hosts/Android

``` ini
Subnet=10.168.10.0/24
```

hosts/Desktop

``` ini
Address={IP}
Port=12978
Subnet=10.168.10.0/24
LocalDiscovery=yes
```

**Comment by Mannshoch** [comment]
Hi again. I have the same happening with an other itun.
 use sometimes an W-Lan with the same range of IP-adresses Like I use in my VPN. Could I somehow told my Tinc or my whole Android to prefer or only use my VPN?
Maybe some script snippet I could add into tinc-up?

**Comment by luckyhacky** [comment]
There is a routing trick if your VPN hosts do not the address of the gateway then it may be possible - but this would be a dirty hack without any garantee.

Example:
- your gateway of WIFI is 10.0.0.1/24
- your subnet of VPN is 10.0.0.x/24

do this over scripts (tinc-up)
delete default route for net (which should be the one for WIFI)
Add a route for gateway (if there is none)
add route for everything: route add net 10.0.0.0 netmask 255.255.255.0 dev tinc

with the addition of dev you can reroute your traffic to use the tinc device. Tinc will convert and tunnel the traffic and send it to the gw.

I hope this helps to solve your issue.

**Comment by Mannshoch** [comment]
Hi @luckyhacky 
Thanks for your helping. I tryed to use it on my Android. Now tinc-up looks like this:

ifconfig $INTERFACE {xxx.xxx.xxx.xxx} netmask 255.255.0.0
route add -net {xxx.xxx.xxx.0} netmask 255.255.255.0 dev $INTERFFACE

I do not get an "Invalid Argument" anymore. But the change it self do not solve the Problem.

If I understand you right i should add a "route del ..." Line too.
route del -net {xxx.xxx.xxx.0} netmask 255.255.255.0 wifi0
ends in "Invalid Argument"

**Comment by luckyhacky** [comment]
route del -net {xxx.xxx.xxx.0} netmask 255.255.255.0 dev wifi0
dev is missing! fixed it in the above line

Can you provide the routing table, if it doesnt work?

**Comment by Mannshoch** [comment]
Was a bit tricky to get these information.
```route -n ```as described on some website not worked but ```ip route list```  does.
```
start tinc-up

ifconfig tun0 10.168.33.11 netmask 255.255.0.0
echo 1 > /proc/sys/net/ipv4/conf/tun0/rp_filter

- To VPN -> tun0
route del -net 10.168.33.0 netmask 255.255.255.0 dev wlan0
Invalid argument
route add -net 10.168.33.0 netmask 255.255.255.0 dev tun0

 - Routing information >ip route list
default via 10.168.250.1 dev wlan0 
default via 10.168.250.1 dev wlan0  metric 308 
10.168.250.0/24 dev wlan0  scope link 
10.168.250.0/24 dev wlan0  proto kernel  scope link  src 10.168.250.193  metric 308 
10.168.250.1 dev wlan0  scope link 
10.168.0.0/16 dev tun0  proto kernel  scope link  src 10.168.33.11 
10.168.33.0/24 dev tun0  scope link 
```

**Comment by luckyhacky** [comment]
try:
ip route del 10.168.33.0/24 dev wlan0
ip route add 10.168.33.0/24 dev tun0

your problem is, that smaller nets are prefered over bigger nets - e.g. /24 is prefered before /16.
