### ISSUE TITLE
Error on Android L

### ISSUE THREAD

**Issue by insanum** [Vilbrekin/tinc_gui#26]
I was playing around with the latest developer preview of Android L and noticed that Tinc is broken. When I start the service I see the following error:

error: only position independent executables (PIE) are supported
tincd terminated

**Comment by chupanoid** [comment]
Hi.
In tinc gui after START, dont work button STOP.
Script tinc-down:
`ifconfig $INTERFACE down

VPN_GATEWAY=192.168.6.30

ip rule del from all lookup 100
ip route del table 100 $REMOTEADDRESS
ip route del table 100 $VPN_GATEWAY dev $INTERFACE 
ip route del table 100 192.168.5.0/27 via $VPN_GATEWAY dev $INTERFACE 
ip route del table 100 192.168.6.0/27 via $VPN_GATEWAY dev $INTERFACE
`

**Comment by chupanoid** [comment]
OS Android 6.0.1 (CM13)
Fix this problem:
`
    public void stopTincd()
    {
        if (_started)
        {
            run("pkill tincd", null);
//            int aPid = getPid();
//            if (aPid != 0)
//            {
//                run("kill " + aPid + " || rm " + getFileStreamPath(PIDFILE), null);
//                Log.d(Tools.TAG, "killed");
//            }
        }
        _debug = false;
        stopForeground(true);
        // Do not call stopSelf(), in order to keep any unflushed logs until GUI activity is back
        checkAndStopSelf();
        // Ensure GUI is updated
        call("tincd terminated.");
    }
`
