### ISSUE TITLE
not working with samsing devices running  SELINUX set to enforcing

### ISSUE THREAD

**Issue by calisro** [Vilbrekin/tinc_gui#28]
My device is rooted and knox is disabled but its a stock rom running SELINUX in enforcing mode (Samsung Galaxy S5). The issue is that the post up scripts do not get run. They fail with an error 127 regardless of what is in them.  This is selinux preventing it.  I tried with and without your variable for command interpretor.  Didn't make a difference.  I can get tinc working by running those scripts after the fact so I know everything is set up properly.

**Comment by alteist** [comment]
I've stuck with same 127 error on S4, but copying tincd binary to /system and symlinking it back for GUI worked for me. Try:
```
su
cp /data/data/org.poirsouille.tinc_gui/files/tincd /system/bin/tincd
mv /data/data/org.poirsouille.tinc_gui/files/tincd /data/data/org.poirsouille.tinc_gui/files/tincd.orig
ln -s /system/bin/tincd /data/data/org.poirsouille.tinc_gui/files/tincd
```
I think authors could include this trick via special button (e.g. "install tincd binary to system") to workaround issue.
