### ISSUE TITLE
Tinc terminate after only one try to connect

### ISSUE THREAD

**Issue by Mannshoch** [Vilbrekin/tinc_gui#31]
I Upgraded my Samsung Galaxy S2 to Cyanogenmod 12. I copied the tinc directory and tried to start Tinc. It only test a connection once and Terminate. 

Tinc has SuperUser right (SuperSU) and the Option "Execute as Super User" is selected.

![tinc](https://cloud.githubusercontent.com/assets/7795891/9196690/1c938cdc-402e-11e5-9d5c-0dee0edf4830.png)

CatLog```
08-11 13:52:34.324 D/tinc_gui( 6716): Refreshing preferences for key 
08-11 13:52:34.360 D/tinc_gui( 6716): Service connected
08-11 13:52:34.750 I/Timeline( 2256): Timeline: Activity_windows_visible id: ActivityRecord{820257c u0 org.poirsouille.tinc_gui/.TincActivity t473} time:328238
08-11 13:52:35.912 I/tinc_gui( 6716): Shell: su; command: id
08-11 13:52:36.368 I/tinc_gui( 6716): Received START intent for tincd service
08-11 13:52:36.369 D/tinc_gui( 6716): Service started
08-11 13:52:36.469 D/tinc_gui( 6716): Returning PID 19254
08-11 13:52:36.492 I/tinc_gui( 6716): Shell: su; command: kill 19254 || rm /data/data/org.poirsouille.tinc_gui/files/tinc.pid
08-11 13:52:37.282 D/tinc_gui( 6716): Network state changed - network available? true
08-11 13:52:37.282 I/tinc_gui( 6716): Network state changed - forcing reconnection
08-11 13:52:37.295 D/tinc_gui( 6716): Returning PID 0
08-11 13:52:37.306 I/tinc_gui( 6716): Shell: su; command: umask 022; exec /data/data/org.poirsouille.tinc_gui/files/tincd -D -d5 -c /storage/sdcard1/tinc --pidfile=/data/data/org.poirsouille.tinc_gui/files/tinc.pid
08-11 13:52:37.573 W/tincd   ( 6966): type=1400 audit(0.0:582): avc: denied { create } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=tcp_socket
08-11 13:52:37.573 W/tincd   ( 6966): type=1400 audit(0.0:583): avc: denied { setopt } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=tcp_socket
08-11 13:52:37.573 W/tincd   ( 6966): type=1400 audit(0.0:584): avc: denied { bind } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=tcp_socket
08-11 13:52:37.573 W/tincd   ( 6966): type=1400 audit(0.0:585): avc: denied { listen } for lport=80 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=tcp_socket
08-11 13:52:37.573 W/tincd   ( 6966): type=1400 audit(0.0:586): avc: denied { setopt } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=udp_socket
08-11 13:52:37.573 W/tincd   ( 6966): type=1400 audit(0.0:587): avc: denied { bind } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=udp_socket
08-11 13:52:37.578 W/tincd   ( 6966): type=1400 audit(0.0:588): avc: denied { connect } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=tcp_socket
08-11 13:52:37.578 W/tincd   ( 6966): type=1400 audit(0.0:589): avc: denied { getopt } for laddr=10.156.250.100 lport=51976 faddr=92.104.100.65 fport=12978 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=tcp_socket
08-11 13:52:39.123 D/tinc_gui( 6716): End of tincd thread
```
What have I to do to get it work?

**Comment by Vilbrekin** [comment]
Hi,

From your traces, it seems you do not use the latest version of tinc_gui,
with the changes needed to cope with lollipop SELinux security settings.
You're especially missing this change:
https://github.com/Vilbrekin/tinc_gui/commit/bb562d8077d0dac746c16e3826a5cf88eee59c9f

Upgrading tinc_gui should solve your issue (
https://github.com/Vilbrekin/tinc_gui/releases).

Rgds,
V

2015-08-11 14:04 GMT+02:00 Mannshoch <notifications@github.com>:

**Comment by Mannshoch** [comment]
OK thanks a lot. 
F-droid tell me that 0.9.12 ist the actual release.
