### ISSUE TITLE
gateway script

### ISSUE THREAD

**Issue by Mannshoch** [Vilbrekin/tinc_gui#33]
I use your Script on my Samsung galaxy S2 with CM5.
> ORIGINAL_GATEWAY=$(for a in $(ip rule show | grep lookup | sed -r 's/.* lookup ([^ ]+).*/\1/'); do ip route show table $a | grep ^default | cut -d ' ' -f 2-5; done | head -1)

I got some Errors

(for a in $(ip rule show | grep lookup | sed -r 's/.* lookup ([^ ]+).*/\1/'); do ip route show table $a | grep ^default | cut -d ' ' -f 2-5; done | head -1)
> cut: standard output: Broken pipe
> cut: standard output: Broken pipe
> cut: standard output: Broken pipe

so I split the commands and got these.
(ip rule show | grep lookup | sed -r s/.* lookup [^ ]+.*/1/)
> _

(ip route show table $a | grep ^default | cut -d   -f 2-5)
> Command line is not complete. Try option "help"

(ip route show | grep ^default | cut -d   -f 2-5)
> _

Have you an Idea what i could do to get Tinc run?

**Comment by luckyhacky** [comment]
If you break up the loop, you have to take care if all requirements are met.

(ip route show table $a | grep ^default | cut -d -f 2-5)
>> $a gets evaluated to "" and command ip failes

This is the root cause in this particular problem but doesn't cover all.

Additionally I think CM5 is quite old :(

**Comment by Mannshoch** [comment]
Oh sorry, there was a mixup between CM12 and Android5 in my mind.
