### ISSUE TITLE
Client on Andorid 6.x  is unable to reach other peers but can reach gw.

### ISSUE THREAD

**Issue by develroo** [Vilbrekin/tinc_gui#39]
Ok this is bugging me because for the life of me I cannot see what it going wrong.

Following [This](http://tinc_gui.poirsouille.org/) guide I set up the routes as they are on my laptop.

> ip route show
> 
> default via 192.168.0.101 dev wlan0  metric 314 
> 10.4.0.0/24 dev tun0  proto kernel  scope link  src 10.4.0.99 
> 192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.150  metric 314 

and

> route -n
> 
> Kernel IP routing table
> Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
> 0.0.0.0         192.168.0.101   0.0.0.0         UG    314    0        0 wlan0
> 10.4.0.0        0.0.0.0         255.255.255.0   U     0      0        0 tun0
> 192.168.0.0     0.0.0.0         255.255.255.0   U     314    0        0 wlan0

This matches my laptops routing table 

> ip route show
> 
> default via 192.168.0.100 dev wlan0  proto static  metric 600 
> 10.4.0.0/24 dev tun4  proto kernel  scope link  src 10.4.0.2 
> 192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.129  metric 600 `
> 
> route -n
> 
> Kernel IP routing table
> Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
> 0.0.0.0         192.168.0.100   0.0.0.0         UG    600    0        0 wlan0
> 10.4.0.0        0.0.0.0         255.255.255.0   U     0      0        0 tun4
> 192.168.0.0     0.0.0.0         255.255.255.0   U     600    0        0 wlan0

I am able to ping the VPN gw at 10.4.0.1 but unable to ping any other peers on the vpn. Is there something else on Android 6.x I need to be aware of to be able to ping peers? 

Any help is appreciated. I know Tinc worked fine on Android 4.3 so I suspect there is something different about 6.x 

Thanks.

**Comment by luckyhacky** [comment]
Read the section in http://tinc_gui.poirsouille.org/ about lollipop.

> ip rule show

Due to activation of SELinux features, there are additional rules which have to be passed.
Will have a look on my settings later and post it.

**Comment by luckyhacky** [comment]
See my post on https://github.com/Vilbrekin/tinc_gui/issues/30

> ip rule add prio 100 from all lookup 100
> ip route add table 100 172.16.200.0/24 dev mako

**Comment by develroo** [comment]
Ahh.. seems that is must be it. Specifically 
`ip route add table 100 $SUBNET/24 dev $INTERFACE`

That only shows if you use 

> ip route show table 100
> 
> default via 192.168.0.101 dev wlan0 
> 10.4.0.0/24 dev tun0  scope link 
> 10.4.0.1 dev tun0  scope link 
> 178.62.230.4 via 192.168.0.101 dev wlan0 

Thanks for that. And yes, if you could amend the documentation it would be helpful.

**Comment by develroo** [comment]
OK for completeness this is the script I ended up using. 
`#!/system/bin/sh`
`VPN_GATEWAY=10.4.0.1`
`IFS=. read -r i1 i2 i3 i4 <<< $VPN_GATEWAY`
`IFS=. read -r m1 m2 m3 m4 <<< "255.255.255.0"`
`VPNSUBNET=``printf "%d.%d.%d.%d\n" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$((i4 & m4))"``

`# Fetch the first default gateway from the current routing tables`
`ORIGINAL_GATEWAY=$(for a in $(ip rule show | grep lookup | sed -r 's/.* lookup ([^ ]+).*/\1/'|uniq -u); do ip route show table $a | grep ^default | cut -d ' ' -f 2-5; done | head -1)`
`echo $ORIGINAL_GATEWAY`

`# Use new routing table 100, to have higher priority than lollipop's ones`
`ip rule add prio 100 from all lookup 100`
`ip route add table 100 $REMOTEADDRESS $ORIGINAL_GATEWAY` 
`ip route add table 100 $VPN_GATEWAY dev $INTERFACE`
`ip route add table 100 "$VPNSUBNET/24" dev $INTERFACE`

Could not work out how to get the netmask from within tinc so I just specified it by hand which I guess you need to do on a per host basis anyway. Either way works for me now so thanks to explaining what went wrong.
